# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siom', '0002_directory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'verbose_name_plural': 'directories'},
        ),
        migrations.AlterField(
            model_name='directory',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='directories', to='siom.Task'),
        ),
    ]
